version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo Installing python packages...
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install -r test_main/requirements.txt
  build:
    commands:
      - echo run tests...
      - python -m pytest test_main