version: 0.2

env:
  variables:
     image: "whisper"
     tag: "flasktest1"

phases:
  pre_build:
    commands:
      - echo Running unit tests...
      - python -m unittest discover -s . -p 'test*.py'
