version: 0.2

env:
  variables:
     image: "whisper"
     tag: "flasktest1"
     
phases:
  pre_build:
    commands:
      - echo Running unit tests...
      - echo Current directory is `pwd`
      - echo PYTHONPATH is $PYTHONPATH
      - export PYTHONPATH="./src_tmp:$PYTHONPATH"
      - echo PYTHONPATH is $PYTHONPATH
      - echo Contents of src directory && ls ./src_tmp
      - python -m unittest discover -s test -p 'test*.py' || exit 1
