version: 0.2

env:
  variables:
     image: "whisper-codebuildtest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - chmod +x build_and_push.sh
      - build_and_push.sh $image
  post_build:
    commands:
      - echo Build completed on `date`
