version: 0.2

env:
  variables:
     image: "whisper"
     tag: "flasktest1"

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - chmod +x build_and_push.sh
      - ./build_and_push.sh $image $AWS_REGION $tag
  post_build:
    commands:
      - echo Build completed on `date`
